### ISSUE TITLE
Delete this app in favor of the People app

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/UserProfile#5]
Similar to https://github.com/StarcounterApps/Registration/issues/11

This app does nothing but requiring maintenance. I would suggest killing it. The ability to edit a users information is integrated into the People app so no functionality will get lost.

**Comment by warpech** [comment]
Thank you @Mackiovello for this initiative. Since we seem to all agree on this one in https://github.com/Starcounter/CompanyTrack/issues/331, I will delete it right away.

**Comment by warpech** [comment]
Copy of this app was saved in Dropbox. Deleting
